CREATE TABLE `usuarios` (
  `id` int(9) NOT NULL AUTO_INCREMENT,
  `cnpj` varchar(20) DEFAULT NULL,
  `cpf` varchar(16) DEFAULT NULL,
  `nome_completo` varchar(250) NOT NULL,
  `inscricao_estadual` varchar(20) DEFAULT NULL,
  `nome_fantasia` varchar(250) DEFAULT NULL,
  `razao_social` varchar(250) DEFAULT NULL,
  `email` varchar(100) DEFAULT NULL,
  `senha` varchar(250) DEFAULT NULL,
  `hash_troca_senha` varchar(250) DEFAULT NULL,
  `telefone` varchar(15) DEFAULT NULL,
  `cep` varchar(9) DEFAULT NULL,
  `endereco` varchar(250) DEFAULT NULL,
  `endereco_numero` int(5) DEFAULT NULL,
  `complemento` varchar(50) DEFAULT NULL,
  `bairro` varchar(50) DEFAULT NULL,
  `cidade` varchar(50) DEFAULT NULL,
  `uf` varchar(2) DEFAULT NULL,
  `situacao` int(1) DEFAULT NULL,
  `tipo_pessoa` int(2) DEFAULT NULL,
  `grupo` int(2) DEFAULT NULL,
  `dt_criacao` datetime DEFAULT NULL,
  `dt_modificado` timestamp,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
